#!/usr/bin/env python3
"""
GTFS → data.js converter
Reads caltrain-ca-us/ GTFS files and writes gtfs/data.js
"""
import csv, json, os, re

BASE  = r"C:\Users\HP\Desktop\Prior Kredit\.proyektlərim\kaliforniya\caltrain-ca-us"
OUT   = r"C:\Users\HP\Desktop\Prior Kredit\.proyektlərim\kaliforniya\gtfs\data.js"

def read_csv(filename):
    path = os.path.join(BASE, filename)
    with open(path, encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))

# ── 1. routes ──────────────────────────────────────────────────────────────
routes_raw = read_csv("routes.txt")
routes = {}
for r in routes_raw:
    rid = r["route_id"].strip()
    routes[rid] = {
        "id":    rid,
        "name":  r["route_long_name"].strip() or r["route_short_name"].strip(),
        "short": r["route_short_name"].strip(),
        "color": r.get("route_color", "").strip() or "cccccc",
    }

# ── 2. trips ───────────────────────────────────────────────────────────────
trips_raw = read_csv("trips.txt")
trips = {}
for t in trips_raw:
    tid = t["trip_id"].strip()
    trips[tid] = {
        "tripId":    tid,
        "routeId":   t["route_id"].strip(),
        "serviceId": t["service_id"].strip(),
        "headsign":  t["trip_headsign"].strip(),
        "direction": t["direction_id"].strip(),
        "shortName": t["trip_short_name"].strip(),
    }

# ── 3. stop_times ──────────────────────────────────────────────────────────
# Keep only the fields the website actually uses
stop_times_raw = read_csv("stop_times.txt")
stop_times = []
for s in stop_times_raw:
    stop_id = s["stop_id"].strip()
    # Skip shuttle/elevator stops — they have no bearing on schedules
    if re.match(r'^(777|BAY-|BEL-|MIL-|SBR-|SJD-|SMT-|TAM-)', stop_id):
        continue
    stop_times.append({
        "trip_id":      s["trip_id"].strip(),
        "arrival_time": s["arrival_time"].strip(),
        "stop_id":      stop_id,
        "stop_seq":     int(s["stop_sequence"]),
    })

print(f"routes: {len(routes)}, trips: {len(trips)}, stop_times: {len(stop_times)}")

# ── 4. Write data.js ───────────────────────────────────────────────────────
routes_js    = json.dumps(routes,     ensure_ascii=False, separators=(',',':'))
trips_js     = json.dumps(trips,      ensure_ascii=False, separators=(',',':'))
stoptimes_js = json.dumps(stop_times, ensure_ascii=False, separators=(',',':'))

js = f"""// AUTO-GENERATED — do not edit by hand
// Source: caltrain-ca-us GTFS feed (generated by build_data.py)
const CALTRAIN_DATA = {{
  routes: {routes_js},
  trips: {trips_js},
  stopTimes: {stoptimes_js}
}};
"""

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write(js)

size_kb = os.path.getsize(OUT) / 1024
print(f"✅  Written to {OUT}  ({size_kb:.1f} KB)")
